services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  WapplerSystems\FormMailchimp\:
    resource: '../Classes/*'

  WapplerSystems\FormMailchimp\Finishers\MailchimpSignInFormFinisher:
    public: true

  WapplerSystems\FormMailchimp\Finishers\MailchimpSignOutFormFinisher:
    public: true

  WapplerSystems\FormMailchimp\Service\MailchimpFormContext:
    public: true
    shared: true

  WapplerSystems\FormMailchimp\Form\Hook\AfterSubmitHook:
    public: true

  MailchimpMarketing\ApiClient:
    public: true
    shared: true